### ISSUE TITLE
Ability to configure asset paths

### ISSUE THREAD

**Issue by jewbetcha** [vseventer/hugo-webpack-boilerplate#1]
I really want to use this, because I've been looking for a way for Webpack to know about images in my HTML templates for my Hugo site. However it would be great if this plugin wasn't so opinionated about where things are/should be stored. We have a custom theme we've developed and reuse, and all assets are in `static/`, in which Webpack is already building/compiling.

Are there any plans to have the ability to configure where `hugo-webpack` looks for assets? Or the ability to specify a custom theme?

Thank you!

**Comment by vseventer** [comment]
The problem is that Hugo copies everything in `static/` to the destination folder, while the point of this plugin is to have Webpack process the images, and then copy the resulting files to the destination folder. Using `static/` wont work, hence this plugin uses a different folder, `static-src/`. I could make this folder configurable, just want to make sure that would fix your issue.

**Comment by jewbetcha** [comment]
Ahh sure, I see. We already have all other asset processing in Webpack configured, so I might try to just mimic your method of processing images and then copying over.
